blocks:
    userprofiling:
        views:
            userprofiling:
                template: EzUserProfilingBlockBundle:blocks:userprofiling.html.twig
                name: User Profiling Block view
